# Generated by Django 5.2.7 on 2026-01-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CHAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(verbose_name='留群編號')),
                ('subject', models.CharField(max_length=200, verbose_name='內文')),
                ('created', models.DateField(auto_now_add=True, verbose_name='建立日期')),
                ('user_name', models.CharField(max_length=64, verbose_name='使用者名稱')),
                ('group_id', models.IntegerField(verbose_name='群組編號')),
            ],
        ),
        migrations.CreateModel(
            name='GROUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(verbose_name='群組名稱')),
                ('desc', models.TextField(verbose_name='說明')),
            ],
        ),
    ]
