# Generated by Django 5.2.9 on 2026-01-03 08:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='creates',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='建立日期'),
            preserve_default=False,
        ),
    ]
