# Generated by Django 5.2.9 on 2026-01-03 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_group_creates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='creates',
        ),
    ]
