# Generated by Django 4.2.27 on 2026-02-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chat_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=64, verbose_name='群組名稱'),
        ),
    ]
